x-common-config:
  &common-config
  network_mode: host
  ipc: host
  restart: unless-stopped

x-dds-envs:
  &dds-envs
  env_file: .env.dds

services:

  ros2router:
    image: husarnet/ros2router:1.6.3
    <<: *common-config
    volumes:
      - ./filterCustom.yaml:/filter.yaml
    environment:
      - VIDEO_CODEC=ffmpeg # can be `ffmpeg`, `theora` or `compressed`
      - ROBOT_NAMESPACE=${ROBOT_NAMESPACE:-robot}
      - USER
      # ==========================
      # envs for Husarnet setup
      # ==========================
      - DISCOVERY_SERVER_LISTENING_PORT=11811
      - DISCOVERY_SERVER_ID=0
      # ==========================
      # envs for LAN setup
      # ==========================
      # - ROS_LOCALHOST_ONLY=0
      # - HUSARNET_PARTICIPANT_ENABLED=false

  rosbot:
    image: husarion/rosbot:humble-0.13.1-20240201
    <<:
      - *common-config
      - *dds-envs
    devices:
      - ${SERIAL_PORT:?err}
      # - /dev/bus/usb/ # FTDI
    environment:
      - ROBOT_NAMESPACE=${ROBOT_NAMESPACE:-robot}
    command: >
      ros2 launch rosbot_bringup combined.launch.py
        mecanum:=${MECANUM:-False}
        serial_port:=$SERIAL_PORT
        serial_baudrate:=576000

  rplidar:
    image: husarion/rplidar:humble-1.0.1-20240104
    <<:
      - *common-config
      - *dds-envs
    devices:
      - /dev/ttyRPLIDAR:/dev/ttyUSB0
    environment:
      - ROBOT_NAMESPACE
    command: >
      ros2 launch /husarion_utils/rplidar.launch.py
        serial_baudrate:=${LIDAR_BAUDRATE:-256000}
        serial_port:=/dev/ttyUSB0
        
  navigation:
    image: husarion/navigation2:humble-1.1.12-20240123
    <<:
      - *common-config
      - *dds-envs
    depends_on:
      rplidar: { condition: service_healthy }
      rosbot: { condition: service_healthy }
    volumes:
      - ./config/nav2_${CONTROLLER:-rpp}_params.yaml:/params.yaml
      - ./maps:/maps
    environment:
      - SAVE_MAP_PERIOD
      - ROBOT_NAMESPACE
    command: >
      ros2 launch /husarion_utils/bringup_launch.py
        slam:=${SLAM:-True}
        params_file:=/params.yaml
        map:=/maps/map.yaml
        use_sim_time:=False

  astra:
    image: husarion/astra:humble-1.1.0-20240111
    <<:
      - *common-config
      - *dds-envs
    devices:
      - /dev/bus/usb/
    volumes:
      - ./params/astra.yaml:/husarion_utils/astra_params.yaml
    command: >
      ros2 launch /husarion_utils/astra.launch.py
        robot_namespace:=${ROBOT_NAMESPACE:-robot}
